# Generated by Django 3.0.2 on 2020-02-12 15:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0002_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('', 'Please Select User'), ('1', 'Hospital'), ('3', 'User')], max_length=50, verbose_name='Booking Type')),
                ('origin_name', models.CharField(max_length=40, verbose_name='Name')),
                ('origin_phone', models.CharField(max_length=40, verbose_name='Phone')),
                ('origin_address', models.CharField(max_length=200, verbose_name='Address')),
                ('origin_geocode', models.CharField(blank=True, max_length=30, null=True, verbose_name='Origin Cordinate')),
                ('destination_name', models.CharField(max_length=40, verbose_name='Name')),
                ('destination_phone', models.CharField(max_length=40, verbose_name='Phone')),
                ('destination_address', models.CharField(max_length=200, verbose_name='Address')),
                ('destination_geocode', models.CharField(blank=True, max_length=30, null=True, verbose_name='Destination Cordinate')),
                ('booking_msg', models.TextField()),
                ('round_trip', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Fare')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.VehicleCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
            options={
                'verbose_name': 'Stops',
                'verbose_name_plural': 'Stops',
                'db_table': 'booking_stops',
            },
        ),
        migrations.CreateModel(
            name='BookingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('feature', models.ManyToManyField(to='setting.Features')),
            ],
            options={
                'verbose_name': 'Booking Features',
                'verbose_name_plural': 'Booking Features',
                'db_table': 'booking_features',
            },
        ),
    ]
