# Generated by Django 3.0.2 on 2020-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Cancel'), (4, 'Delete')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bookingstop',
            name='stop_geocode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Stop Cordinate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_msg',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
