# Generated by Django 3.0.2 on 2020-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200215_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='round_trip',
            field=models.IntegerField(default=False),
        ),
    ]
