# Generated by Django 3.0.2 on 2020-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200215_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='round_trip',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
