# Generated by Django 3.0.2 on 2020-02-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200215_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
